
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action justifyFillAction;
	
	private global::Gtk.Action justifyFillAction1;
	
	private global::Gtk.Action justifyFillAction2;
	
	private global::Gtk.Action okAction;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeview1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Toolbar toolbar3;
	
	private global::Gtk.Entry entry3;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Toolbar toolbar4;
	
	private global::Gtk.Entry entry4;
	
	private global::Gtk.Toolbar toolbar5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.justifyFillAction = new global::Gtk.Action ("justifyFillAction", null, null, "gtk-justify-fill");
		w1.Add (this.justifyFillAction, null);
		this.justifyFillAction1 = new global::Gtk.Action ("justifyFillAction1", null, null, "gtk-justify-fill");
		w1.Add (this.justifyFillAction1, null);
		this.justifyFillAction2 = new global::Gtk.Action ("justifyFillAction2", null, null, "gtk-justify-fill");
		w1.Add (this.justifyFillAction2, null);
		this.okAction = new global::Gtk.Action ("okAction", null, null, "gtk-ok");
		w1.Add (this.okAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView ();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add (this.treeview1);
		this.table1.Add (this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar3'><toolitem name='justifyFillAction1' action='justifyFillAction1'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.hbox2.Add (this.toolbar3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.toolbar3]));
		w4.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.hbox2.Add (this.entry3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry3]));
		w5.Position = 1;
		this.table1.Add (this.hbox2);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox2]));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar4'><toolitem name='justifyFillAction2' action='justifyFillAction2'/></toolbar></ui>");
		this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar4")));
		this.toolbar4.Name = "toolbar4";
		this.toolbar4.ShowArrow = false;
		this.hbox3.Add (this.toolbar4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.toolbar4]));
		w7.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.hbox3.Add (this.entry4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry4]));
		w8.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar5'><toolitem name='okAction' action='okAction'/></toolbar></ui>");
		this.toolbar5 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar5")));
		this.toolbar5.Name = "toolbar5";
		this.toolbar5.ShowArrow = false;
		this.hbox3.Add (this.toolbar5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.toolbar5]));
		w9.Position = 2;
		this.table1.Add (this.hbox3);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox3]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 707;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
